In [2]:
import torch

In [2]:
policy = torch.jit.load("/home/conang/quadruped/unitree_rl_gym/deploy/pre_train/go2/model_1500.pt")

RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found

In [ ]:
model = torch.load("/home/conang/quadruped/unitree_rl_gym/deploy/pre_train/go2/model_1500.pt")

In [13]:
model

{'model_state_dict': OrderedDict([('std',
               tensor([0.4886, 0.7988, 0.6604, 0.5108, 0.7436, 0.6977, 0.4730, 0.6337, 0.6421,
                       0.4714, 0.6132, 0.6446], device='cuda:0')),
              ('actor.0.weight',
               tensor([[ 0.0415, -0.1453,  0.0917,  ..., -0.0269,  0.0210, -0.1322],
                       [-0.0094, -0.1135,  0.1085,  ..., -0.0436, -0.0067,  0.0860],
                       [ 0.0351,  0.0568,  0.0080,  ...,  0.0345,  0.0600, -0.0250],
                       ...,
                       [-0.1051, -0.2534, -0.0615,  ...,  0.0004, -0.0676, -0.0454],
                       [-0.1793, -0.0210, -0.0619,  ..., -0.0458,  0.1073, -0.0372],
                       [ 0.0067, -0.1131,  0.2656,  ..., -0.1293,  0.0400, -0.0201]],
                      device='cuda:0')),
              ('actor.0.bias',
               tensor([-1.2350e-01, -2.5592e-01,  4.8214e-02, -5.2453e-02,  1.0534e-01,
                       -2.9968e-01, -1.2353e-01, -1.0768e-01,  8

In [ ]:
model['model_state_dict']['actor.0.bias']

OrderedDict([('std',
              tensor([0.4886, 0.7988, 0.6604, 0.5108, 0.7436, 0.6977, 0.4730, 0.6337, 0.6421,
                      0.4714, 0.6132, 0.6446], device='cuda:0')),
             ('actor.0.weight',
              tensor([[ 0.0415, -0.1453,  0.0917,  ..., -0.0269,  0.0210, -0.1322],
                      [-0.0094, -0.1135,  0.1085,  ..., -0.0436, -0.0067,  0.0860],
                      [ 0.0351,  0.0568,  0.0080,  ...,  0.0345,  0.0600, -0.0250],
                      ...,
                      [-0.1051, -0.2534, -0.0615,  ...,  0.0004, -0.0676, -0.0454],
                      [-0.1793, -0.0210, -0.0619,  ..., -0.0458,  0.1073, -0.0372],
                      [ 0.0067, -0.1131,  0.2656,  ..., -0.1293,  0.0400, -0.0201]],
                     device='cuda:0')),
             ('actor.0.bias',
              tensor([-1.2350e-01, -2.5592e-01,  4.8214e-02, -5.2453e-02,  1.0534e-01,
                      -2.9968e-01, -1.2353e-01, -1.0768e-01,  8.4534e-02,  9.2289e-02,
           

In [10]:
test_model = torch.load("/home/conang/quadruped/unitree_rl_gym/deploy/pre_train/g1/motion.pt")

In [11]:
test_model

RecursiveScriptModule(
  original_name=PolicyExporterLSTM
  (actor): RecursiveScriptModule(
    original_name=Sequential
    (0): RecursiveScriptModule(original_name=Linear)
    (1): RecursiveScriptModule(original_name=ELU)
    (2): RecursiveScriptModule(original_name=Linear)
  )
  (memory): RecursiveScriptModule(original_name=LSTM)
)

In [3]:
policy = torch.jit.load("/home/conang/quadruped/unitree_rl_gym/logs/rough_go2/exported/policies/policy_1.pt")

In [ ]:
policy.shape

AttributeError: 'RecursiveScriptModule' object has no attribute 'shape'